[project]
name = "oodo-assign"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymupdf>=1.23.0",
    "pdfplumber>=0.10.0",
    "click>=8.0.0"
]
